### ISSUE TITLE
Does this aws-s3 plugin work with grails 2.5.6?

### ISSUE THREAD

**Issue by subhash279** [agorapulse/grails-aws-sdk#106]
Hi,
Can you pls let me know if this is for grails 3 only or even for grails 2.
Thanks

**Comment by musketyr** [comment]
hi. latest releases are for Grails 3.x only

I believe this is the latest version compatible with Grails 2.x 

https://github.com/agorapulse/grails-aws-sdk/releases/tag/2.1.19

S3 barely changes so you might find everything you need inside this version

**Comment by sumit-prajapati** [comment]
Hi,

What is the latest compatible version of the current version of the plugin? 
The plugin works with grails **3.3.x** and later.  
But I have some application with grails **3.1.x** and **3.2.x** and it is not working for those versions.

Could you please provide the compatible grails version for the plugin and if possible could you also mention the same in the **Read me** page as I could not find it there.

Thanks

**Comment by musketyr** [comment]
hi @sumit-prajapati, I've added the compatibility table in this commit d8a24162a688905be02309d83182454d441e26ab. I'm unable to test many Grails version against many version of the plugins. the only advice I can give you is just taking a look at the release page and try to step back the version unless you find one which works well with the old app. if you find it will be great if you can share it as a PR to the readme file.

**Comment by sumit-prajapati** [comment]
Thanks a lot @musketyr for your reply. Actually we are currently using the old version of the plugin for s3 operation and it is working fine. But currently we are implementing kinesis service and kinesis client library (KCL) for consumer application and this plugin was exactly what I was looking for grails. 

For grails 2 also I have tried to implement the latest version of this plugin by making slight modification. Everything works fine for consumer and producer end and calling the stream data. The only issue I am facing is with session as I am unable to get session variable for CRUD operation
```

def sessionFactory

def handleEvent(MyEvent event) {
        log.debug "Handling event ${event}"
        // Put you consumer business logic here
       // Method for CRUD operations
      sessionFactory.openSession() --> Cannot invoke openSession() on null object
}
```
I may be using it wrong so any help will be greatly appreciated.

Thanks

**Comment by musketyr** [comment]
is `MyEvent` a GORM entity? in that case, the following piece of code should help you:

```
MyEvent.withNewSession {

}
```
see https://docs.grails.org/latest/ref/Domain%20Classes/withNewSession.html

**Comment by sumit-prajapati** [comment]
Thanks @musketyr. This is exactly what I was looking for. Worked like a charm :)

**Comment by riteshranjan** [comment]
Hi 
 will this plugin works for grails 4, can you please let me know

**Comment by njacque2** [comment]
hey @musketyr im also using grails 2.5.6 and trying to add the plugin to my BuildConfig.groovy file. However i have a service that uses RestBuilder() and now it will not work properly. Any help with this?

**Comment by musketyr** [comment]
@njacque2 have you tried to migrate your `RestBuilder` code to e.g. https://http-builder-ng.github.io/http-builder-ng/asciidoc/html5/. Or Micronaut HTTP Client but in that case, I'm not sure if it would be possible to add Micronaut library in such an old app.

**Comment by musketyr** [comment]
Closed due inactivity
