### ISSUE TITLE
Allow endpoint configuration

### ISSUE THREAD

**Issue by jrAtAustin** [agorapulse/grails-aws-sdk#109]
This is not a big deal but it would be nice if you could override the AmazonSQSClient endpoint configuration like is possible with the other settings such as region. I was developing using Localstack and being able to set the endpoint in the configuration by environment would be nice. To workaround this I subclassed AmazonSQSService and overrode afterPropertiesSet().

```
    @Override
    void afterPropertiesSet() throws Exception {
        // Set region
        Region region = AwsClientUtil.buildRegion(config, serviceConfig)
        assert region?.isServiceSupported(SERVICE_NAME as String)

        // Create client
        client = AmazonSQSClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(LOCAL_STACK_SQS_ENDPOINT, region.name))
                .withCredentials(AwsClientUtil.buildCredentials(config, serviceConfig))
                .withClientConfiguration(AwsClientUtil.buildClientConfiguration(config, serviceConfig))
                .build()

        defaultQueueName = serviceConfig?.queue ?: ''
    }
```

**Comment by musketyr** [comment]
hi, it should be possible by changing `proxyPort` and `proxyHost` settings.

```
grails:
    plugin:
        awssdk:
            sqs:
                proxyHost: localhost
                proxyPort: <localstack port>
```

let me know if it works for you.

if you are working with Grails 4 (or even older) then you can use [Micronaut AWS SDK](https://agorapulse.github.io/micronaut-aws-sdk/#_simple_queue_service_sqs) instead which already has the endpoint option.
