### ISSUE TITLE
DynamoDB with only hash key isn't supported

### ISSUE THREAD

**Issue by jogee** [agorapulse/grails-aws-sdk#112]
Hello,

When I try to use the DynamoDB integration plugin with only a hash key it doesn't work. I bump into the error that a range key has to be selected while this is not required according to the AWS documentation.

Regards.

**Comment by musketyr** [comment]
hi, you are right. this has been addressed in [Microaut AWS SDK](https://github.com/agorapulse/micronaut-aws-sdk). is there any chance you can use the Micronaut library instead? [Micronaut Grails]( https://github.com/agorapulse/micronaut-grails) works usually well from Grails 3.x.

**Comment by jogee** [comment]
I'll try that options, thanks.
