### ISSUE TITLE
Whether to consider compatibility with aws API version 2?

### ISSUE THREAD

**Issue by wuzhongdehua** [agorapulse/grails-aws-sdk#113]
https://mvnrepository.com/artifact/software.amazon.awssdk

**Comment by musketyr** [comment]
Hi, there are no plans at the moment as the main effort is now towards [the Micronaut version of the library](https://github.com/agorapulse/micronaut-aws-sdk). 

There are several parts already migrated but I'm waiting for having all of them before updating the docs.

https://github.com/agorapulse/micronaut-aws-sdk/tree/master/subprojects

**Comment by wuzhongdehua** [comment]
> Hi, there are no plans at the moment as the main effort is now towards [the Micronaut version of the library](https://github.com/agorapulse/micronaut-aws-sdk).
> 
> There are several parts already migrated but I'm waiting for having all of them before updating the docs.
> 
> https://github.com/agorapulse/micronaut-aws-sdk/tree/master/subprojects

Thank you for your reply.
