### ISSUE TITLE
https://dl.bintray.com/agorapulse got 403

### ISSUE THREAD

**Issue by redwolfgang24** [agorapulse/grails-aws-sdk#119]
Hi guys, I'm not sure if this is the right place to ask this one about _**https://dl.bintray.com/agorapulse/libs/org/grails/plugins/views-gradle/2.0.0.BUILD-SNAPSHOT/maven-metadata.xml**_  which is always returning 403. Is bintray still accessible by now? I ask this questions since views-gradle Build snapshots is from agorapulse bintray. Thank you in advance.

**Comment by musketyr** [comment]
Hi. Bintray in now in silicon heaven. we still haven't figure out where to move the artifacts. They are currently published into GitHub Repository but these requires authentication.

**Comment by musketyr** [comment]
But related to views plugin - the error is not related to our repository - there's an ongoing issue with the Grails repo - you are supposed to use  https://repo.grails.org/artifactory/core as a replacement for a workaround

![Snímek obrazovky 2021-06-07 v 8 15 47](https://user-images.githubusercontent.com/660405/120968010-924d5580-c768-11eb-8fd3-f171b8f54404.png)

**Comment by redwolfgang24** [comment]
Thanks @musketyr this one solves my issue, thanks a lot.

**Comment by redwolfgang24** [comment]
@musketyr Do you have any idea why **_./grailsw_** wrapper throw this error _**You must be connected to the internet the first time you use the Grails wrapper**_ in my bitbucket CI/CD? I got this error when I started using [https://repo.grails.org/artifactory/core](https://repo.grails.org/artifactory/core) as alternative to fix the issue. I don't really know why grails wrapper is not working in the pipelines but working in my local machine. Thank you in advance :)

**Comment by musketyr** [comment]
I'm afraid that the tool is using the broken repository internally. For example, I'm unable to create new project with `grails create-app`

**Comment by redwolfgang24** [comment]
@musketyr do you have any idea how we can resolve this issue?

**Comment by musketyr** [comment]
Not really, try ask at Grails Community Slack channel, that's where Puneet has announced it.

**Comment by redwolfgang24** [comment]
@musketyr I just joined the community, hope someone can help us to fix this issue. Thank you @musketyr very much :)

**Comment by musketyr** [comment]
I'm just posting here a link to the official issue

https://github.com/grails/grails-core/issues/11825
