### ISSUE TITLE
SQS Init function doesn't set default name

### ISSUE THREAD

**Issue by patrickclarkfish** [agorapulse/grails-aws-sdk#121]
## Description:
The init function, when used documented in the readme for the SQS plugin, is called prior to afterPropertiesSet. This causes the application settings to override any name passed in through the init function (including not set) and makes the plugin unable to support more than a single queue, without hard coding queue names into the send message function. This happens because in grails, `@PostConstruct` is handled before `afterPropertiesSet()`. 

## Workaround:
This can be worked around by overriding the afterPropertiesSet function, calling the base function, then calling init.

```
class myCustomSQSService extends AmazonSQSService{
	static final String QUEUE_NAME = "myQueue"

	void afterPropertiesSet() {
		super.afterPropertiesSet()
		init(QUEUE_NAME)
	}
}
```

**Comment by musketyr** [comment]
Thanks for letting us know! I have updated the documentation but still, I would recommend you to switch to [Micronaut AWS SDK which can be easily used from Grails 4](https://agorapulse.github.io/micronaut-aws-sdk/#_simple_queue_service_sqs).
