### ISSUE TITLE
Not supporting Grails 5.

### ISSUE THREAD

**Issue by hhovhannisyan** [agorapulse/grails-aws-sdk#122]
Hi there, as I can see we don't have support for Grails 5. x.x. Could you please confirm that is in progress or it will not support Grails 5 what then we should use Instead?

Thanks in advance

**Comment by musketyr** [comment]
Hi, this is correct. As mentioned [here](https://github.com/agorapulse/grails-aws-sdk#compatibilty) you should be using [Micronaut AWS SDK](https://agorapulse.github.io/micronaut-aws-sdk/) instead.

**Comment by hhovhannisyan** [comment]
Thanks, @musketyr. Are you confirming that [micronaut-aws-sdk](https://agorapulse.github.io/micronaut-aws-sdk/) have support for Grails 5 and specify which version to use, please? Because [here](https://github.com/agorapulse/grails-aws-sdk#compatibilty) in table charts only information about Grails 4 and not Grails 4+.
```
NOTE: For Grails 4 you should consider migrating to Micronaut AWS SDK as Miconaut is now the first-class citizen in Grails. Use -micronaut-1.2 releases for Grails 4.0.x.
```

**Comment by musketyr** [comment]
You are right. I've updated the docs. The latest version should work with Grails 5 and Micronaut 3.
