### ISSUE TITLE
mavenRepo gives 502 bad gateway

### ISSUE THREAD

**Issue by saimonefcs** [agorapulse/grails-aws-sdk#123]
Hi there,
the URL http://dl.bintray.com/agorapulse/libs needed to download the dependency gives 502 Bad Gateway. 
Did you move the repo somewhere else or am I just doing something wrong?

BuidConfig.groovy:
`repositories {
        ...
        mavenRepo "http://dl.bintray.com/agorapulse/libs"
        ...
}`
Error:
`Resolve error obtaining dependencies: Could not transfer artifact agorapulse.libs:groovy-aws-sdk-util:jar:1.1 from/to dl_bintray_com_agorapulse_libs (http://dl.bintray.com/agorapulse/libs): Bad Gateway (502)`

Using grails 2.5.5 and Java 8

Kind regards,
Andrea.

**Comment by musketyr** [comment]
Hi,

we haven't but JFrog had killed the Bintray service. The latest artifacts are available via JitPack but I'm afraid the older versions you would need to run with Grails 2.x are not cached anywhere.

```
repositories { 
     maven { url 'https://jitpack.io' }
}
```
Best,
Vlad
