### ISSUE TITLE
This Plugin Does Not Support CloudFrontUrlSigner 

### ISSUE THREAD

**Issue by AhamedSKR** [agorapulse/grails-aws-sdk#30]
aws-sdk-java 1.9.14 have a CloudFrontUrlSigner service to generate cloudfront signed url.
this plugin use the same aws-sdk-java 1.9.14 or not.
how to generate cloudfront signed url using this plugin.

**Comment by benorama** [comment]
Yes, this plugin is just a wrapper around the aws-sdk-java lib (current version is 1.9.14).
So you should be able to use CloudFrontUrlSigner, as explained in java doc:
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudfront/CloudFrontUrlSigner.html

**Comment by AhamedSKR** [comment]
Your Example Enum Static Methods getCustomSignedURL,getCannedSignedURL Not in SDK it changed in(getSignedURLWithCannedPolicy,getSignedURLWithCustomPolicy)

 Protocol protocol = Protocol.http;
 String distributionDomain = "d1b2c3a4g5h6.cloudfront.net";
 File privateKeyFile = new File("/path/to/cfcurlCloud/rsa-private-key.pem");
 String s3ObjectKey = "/a/b/images.jpeg";
 String keyPairId = "APKAJCEOKRHC3XIVU5NA";
 Date dateLessThan = DateUtils.parseIso8601Date("2012-11-14T22:20:00.000Z");
 Date dateGreaterThan = DateUtils.parseIso8601Date("2011-11-14T22:20:00.000Z")
 String ipRange = "192.168.0.1/24";
 
 String url1 = CloudFrontUrlSigner.getCannedSignedURL(protocol, distributionDomain, privateKeyFile,
              s3ObjectKey, keyPairId, dateLessThan);
      
 String url2 = CloudFrontUrlSigner.getCustomSignedURL(protocol, distributionDomain, privateKeyFile,
              s3ObjectKey, keyPairId, dateLessThan, dateGreaterThan, ipRange);
