### ISSUE TITLE
Create Directory Documentation/Example

### ISSUE THREAD

**Issue by johnpfeifer4** [agorapulse/grails-aws-sdk#31]
I'm trying to created directories but I can't seem to find an example.  I know this isn't an issue per se, but I was hoping that you could point me in the right direction.  I've tried something like this...

    public void createDirectory(String directoryName) {
        ObjectMetadata metadata = new ObjectMetadata();
        metadata.setContentLength(0);

        InputStream emptyContent = new ByteArrayInputStream(new byte[0]);
        amazonWebService.s3.putObject(new PutObjectRequest("${grailsApplication.config.awsBucket}", directoryName, emptyContent, metadata).withCannedAcl(CannedAccessControlList.PublicRead))
    }

But it creates a file rather than a directory.  I tried creating a bucket with name "root-bucket/folder" and it complains about the "/".  Any help would be greatly appreciated.

Thanks!

**Comment by benorama** [comment]
I don't know if you can create "directories" in S3.
There is only one "directory" which is the bucket (root path).
The other "directories" in the path are virtual and depends on file keys.

**Comment by johnpfeifer4** [comment]
I think I figured it out... You don't have to create the "directory" before you upload a file.  If you create file "foo/bar/x.pdf" it will automatically create those directories... Or at least the client that I'm using, S3 Bucket Explorer, will allow you to navigate them properly.
