### ISSUE TITLE
getServiceAbbreviation is not complete

### ISSUE THREAD

**Issue by jagedn** [agorapulse/grails-aws-sdk#34]
getServiceAbbreviation only check a few service.
if the serviceAbbreviation is not correct the Region can return false to isServiceSupported

it need to be change to something similar to:

    private String getServiceAbbreviation(String service) {
        switch(service) {
            case 'cloudWatch':
                ServiceAbbreviations.CloudWatch
                break
            case 'ses':
                ServiceAbbreviations.Email
                break
            case 's3Encryption':
                ServiceAbbreviations.S3
                break
            case 'autoScaling':
                ServiceAbbreviations.Autoscaling
                break
            case 'cognitoIdentity':
                ServiceAbbreviations.CognitoIdentity
                break
            case 'cognitoSync':
                ServiceAbbreviations.CognitoSync
                break
            case 'cloudFormation':
                ServiceAbbreviations.CloudFormation
                break
            case 'cloudFront':
                ServiceAbbreviations.CloudFront
                break
            case 'cloudSearch':
                ServiceAbbreviations.CloudSearch
                break
            case 'cloudTrail':
                ServiceAbbreviations.CloudTrail
                break
            case 'cloudWatch':
                ServiceAbbreviations.CloudWatch
                break
            case 'codeDeploy':
                ServiceAbbreviations.CodeDeploy
                break
            case 'config':
                ServiceAbbreviations.Config
                break
            case 'dynamoDB':
                ServiceAbbreviations.Dynamodb
                break
            case 'ec2':
                ServiceAbbreviations.EC2
                break
            case 'elasticBeanstalk':
                ServiceAbbreviations.ElasticBeanstalk
                break
            case 'elastiCache':
                ServiceAbbreviations.Elasticache
                break
            case 'elasticLoadBalancing':
                ServiceAbbreviations.ElasticLoadbalancing
                break
            case 'elasticMapReduce':
                ServiceAbbreviations.ElasticMapReduce
                break
            case 'elasticTranscoder':
                ServiceAbbreviations.ElasticTranscoder
                break
            case 'glacier':
                ServiceAbbreviations.Glacier
                break
            case 'iam':
                ServiceAbbreviations.IAM
                break
            case 'importExport':
                ServiceAbbreviations.ImportExport
                break
            case 'kinesis':
                ServiceAbbreviations.Kinesis
                break
            case 'kms':
                ServiceAbbreviations.KeyManagementService
                break
            case 'opsWorks':
                ServiceAbbreviations.Opsworks
                break
            case 'rds':
                ServiceAbbreviations.RDS
                break
            case 'redshift':
                ServiceAbbreviations.RedShift
                break
            case 'route53':
                ServiceAbbreviations.Route53
                break
            case 's3':
                ServiceAbbreviations.S3
                break
            case 'sdb':
                ServiceAbbreviations.SimpleDB
                break
            case 'ses':
                ServiceAbbreviations.Email
                break
            case 'sns':
                ServiceAbbreviations.SNS
                break
            case 'sqs':
                ServiceAbbreviations.SQS
                break
            case 'sts':
                ServiceAbbreviations.STS
                break
            case 'storageGateway':
                ServiceAbbreviations.StorageGateway
                break
            case 'swf':
                ServiceAbbreviations.SimpleWorkflow
                break
            default:
                service.toLowerCase()
        }
    }

**Comment by jagedn** [comment]
or use ServiceAbbreviations.XXXXX as the argument to getServiceClient method

AmazonAutoScalingAsyncClient getAutoScalingAsync(regionName = '') {
        getServiceClient(ServiceAbbreviations.Autoscaling, regionName, true) as AmazonAutoScalingAsyncClient
    }

**Comment by benorama** [comment]
I'll check that, thanks!

**Comment by benorama** [comment]
ServiceAbbreviations was added later in Java AWS SDK, so it would have been a breaking change to the plugin to use ServiceAbbreviations (for config keys).
That's the reason why I kept distinct service name/config keys.
But in most cases, `service.toLowerCase()` should return the correct service abbreviation.

`getServiceAbbreviation` was added to handle few exceptions such as CloudWatch (-> monitoring) or SES (-> email).
I have to update this method to add Cognito service abbreviation exception.
Do you have other example of existing AWS SDK clients returning an incorrect service abbreviation?

**Comment by jagedn** [comment]
precisamente yo estaba jugando con cognito cuando vi el problema porque la Region siempre me decia que no soportaba el servicio.
puedo revisar el resto de id para ver que coincidan todos.

regards (and good job)

**Comment by jagedn** [comment]
I was just playing with Cognito when I saw the problem because the Region always said I could not stand the service.
I can check the rest of id to see that match all
