### ISSUE TITLE
Grails 3

### ISSUE THREAD

**Issue by abdielou** [agorapulse/grails-aws-sdk#36]
Hi there,

Will this work with Grails 3? If so, how do you configure it in build.gradle?

**Comment by benorama** [comment]
Yes, I've created a grails3 branch.
So you can give a try (follow the README instructions):
https://github.com/agorapulse/grails-aws-sdk/tree/grails3

**Comment by abdielou** [comment]
Works! Thanks

**Comment by ortimanu** [comment]
Hi, how can I make this work in the latest Grails 3.1.0.M1? What is the last version of the plugin for Grails 3.0? (fyi... I hate Bintray ;)).
