### ISSUE TITLE
Transfer manager uploads with no public permissions

### ISSUE THREAD

**Issue by olegtim** [agorapulse/grails-aws-sdk#37]
Thanks for working on the much needed plugin for Grails!

Need to make a small correction to docs in S3, Transfer manager section: 

"Upload asynchronously a file with public read permissions." is wrong as the code provided will upload with no public permissions:

Upload upload = amazonWebService.transferManager.upload(new PutObjectRequest('some-grails-bucket', 'somePath/someKey.jpg', new File('/Users/ben/Desktop/photo.jpg'))) 

Can either change doc description or code to add:
.withCannedAcl(CannedAccessControlList.PublicRead

**Comment by benorama** [comment]
Docs are updated.
Thanks for the feedback!
