### ISSUE TITLE
I can not refresh my dependencies

### ISSUE THREAD

**Issue by viniciuszim** [agorapulse/grails-aws-sdk#39]
Hi... When I try to refresh my dependencies (grails refresh-dependencies) I have the error below:

:: problems summary ::
:::: ERRORS
	Server access Error: Received fatal alert: internal_error url=https://grails.org/plugins/grails-aws-sdk/tags/RELEASE_1_7_7/aws-sdk-1.7.7.pom
	Server access Error: Received fatal alert: internal_error url=https://grails.org/plugins/grails-aws-sdk/tags/RELEASE_1_7_7/grails-aws-sdk-1.7.7.zip
	Server access Error: Received fatal alert: internal_error url=https://grails.org/plugins/grails-aws-elastic-beanstalk/tags/RELEASE_0_3-SNAPSHOT/aws-elastic-beanstalk-0.3-SNAPSHOT.pom
	Server access Error: Received fatal alert: internal_error url=https://grails.org/plugins/grails-aws-elastic-beanstalk/tags/RELEASE_0_3-SNAPSHOT/grails-aws-elastic-beanstalk-0.3-SNAPSHOT.jar

I searched a lot but I didn't find right answer.

I'm using grails 2.2.4 for this project

Thanks

**Comment by benorama** [comment]
Are you using the latest release? (1.10.11)

**Comment by viniciuszim** [comment]
aws-sdk-1.7.7 .... I can't update for now
