### ISSUE TITLE
"Another unnamed CacheManager"-issue when deploying to Elastic Beanstalk

### ISSUE THREAD

**Issue by vahurh** [agorapulse/grails-aws-sdk#41]
Hey, I started getting a whole bunch of cache-related issues when using this plugin for Grails 3 and deploying to AWS EB. I initially thought it was to do with other plugins, but after replacing this plugin with the AWS SDK for Java everything started working again. (I also tried reverting from Grails 3.1.4 -->  3.1.1, but didn't help)

The error that started it all was:
`Caused by: org.hibernate.cache.CacheException: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.`

I don't know how helpful this post is, but I spend a lot of time debugging it, so might as well post it here in case someone else encounters something similar. A bit detailed documentation on the error and what I tried before replacing the plugin:
http://stackoverflow.com/questions/36434773/another-unnamed-cachemanager-already-exists-in-the-same-vm-error-when-deployin/36662357
https://github.com/grails-plugins/grails-database-migration/issues/62

**Comment by benorama** [comment]
That's crazy...
I rebuilt the plugin with Grails 3.1.5, aws-sdk 1.10.69 and removed the cache plugin.
Let me know if it solve the issue.

FYI, I'm currently working on a suite of aws-sdk plugins to replace this one (which pulls all the aws-sdk, which starts to become pretty big).

The objective is to provide optimized plugins, with the only required aws-sdk- lib and a set of Grails utility services/classes for each major Amazon service.
It's a work in progress, for example here is the SQS plugin:
https://github.com/agorapulse/grails-aws-sdk-sqs

**Comment by benorama** [comment]
I close this issue since you can now use the optimized AWS plugins for Grails3:
https://medium.com/@benorama/aws-sdk-plugins-for-grails-3-cc7f910fdc0d#.82945fvd6
