### ISSUE TITLE
Allow to exclude not needed aws services in order to decrease the final war size

### ISSUE THREAD

**Issue by jglapa** [agorapulse/grails-aws-sdk#43]
I'm in a situation where I'm using your plugin but only `S3` service at the moment. ( I know there are other plugins offering only S3 access but I would prefer to continue to use this plugin just in case I require to use something additional). 
The problem I have right now is that my final war has all the `aws-java-sdk-*.jars` and almost all of them are completely unnecessary.

I cannot exclude them since  the [AmazonWebService](https://github.com/agorapulse/grails-aws-sdk/blob/master/grails-app/services/grails/plugin/awssdk/AmazonWebService.groovy) requires all the classes in order to provide type information.

I started tinkering around the idea of dynamically exposing the services when the  appropriate class is on the classpath.

This would be achieved in the following way:
```groovy
...
    @PostConstruct
    void init() {
        ['S3'      : 'com.amazonaws.services.s3.AmazonS3Client',
         'EC2'     : 'com.amazonaws.services.ec2.AmazonEC2Client',
         'EC2Async': 'com.amazonaws.services.ec2.AmazonEC2AsyncClient'
         // all the rest...
        ].each { serviceName, serviceClassName ->
            try {
                def serviceClazz = Class.forName(serviceClassName)
                def async = serviceName.endsWith('Async')
                if (serviceClazz) {
                    this.metaClass."get${serviceName}${async ? 'Async' : ''}" = { regionName = '' ->
                        getServiceClient(serviceName.toLowerCase(), regionName, serviceClazz, async)
                    }
                }
            } catch (ClassNotFoundException cnfe) {
                log.warn "$serviceClassName not available"
            }
        }
    }
 ...
 ```

When the plugin is initialized it iterates through the lookup table of all possible AWS service class names (perhaps the explicit name for the service is not needed). And then checks if the given class name is available. If yes it creates a dynamic method via metaClass that calls the getServiceClient method with the additional Class parameter.
In this method we instantiate the service with  `Class.newInstance` and pass all the arguments as we did before. This whole switch can be simplified since almost every service will be instantiated in the same way.

 ```groovy
 private AmazonWebServiceClient getServiceClient(String service, String regionName = '', Class serviceClazz, Boolean async = false) {
       ....

            switch (service) {
            	...
                case 'ec2':
                    client = async ? serviceClazz.newInstance(credentials, configuration, executorService) : serviceClazz.newInstance(credentials, configuration)
                    break
                ...

 ```

By doing it that way get rid of all the imported types. The only thing remaining is the `DynamoDBMapper` but this is used for tests so perhaps it could be moved somewhere outside...

Having this in place I can then use the plugin in my application in the following way:

```BuildConfig.groovy
 plugins {
 ...
compile ":aws-sdk:1.10.44", {
	 excludes 'aws-java-sdk','aws-java-sdk-efs','aws-java-sdk-waf','aws-java-sdk-cloudformation',
            'aws-java-sdk-cloudwatch','aws-java-sdk-elasticbeanstalk','aws-java-sdk-ssm',
            'aws-java-sdk-swf-libraries','aws-java-sdk-codecommit','aws-java-sdk-ec2','aws-java-sdk-redshift', .....
...

}
```

I just need the ` 'aws-java-sdk-s3', 'aws-java-sdk-core', 'aws-java-sdk-dynamodb'` dependencies to have a working s3 service.

The small prototype I did seems to be working fine and thanks to the `exclude` usage I was able to slim down my final war by about 20MB.

The only drawback is that since the methods are now dynamically inserted there is not type information for IDE. We can of course cast it each time to get it : `((com.amazonaws.services.s3.AmazonS3Client)amazonWebService.s3)`

Would be this considered as an improvement? I could prepare a PR but I would need to know if there is any need for something like that.
I would be also interested if there are possibly other approaches to solve this problem?

**Comment by benorama** [comment]
Indeed, it has always been an issue.
That's why I've created multiple plugins for Grails3:
https://medium.com/@benorama/aws-sdk-plugins-for-grails-3-cc7f910fdc0d#.w5c5d8ss6

So my personal recommandation: use Grails3 and those plugins, if you can :)

On our side, we are currently migrating all our apps to Grails3. By the end of the year, we will be most probably only running on Grails3, so I don't plan to make a lot of improvements to this Grails2 plugin.

**Comment by jglapa** [comment]
I'm a bit far from Grails3 migration but if the support is going to be dropped then I guess I'll just wire the AWS S3 manually without a plugin then. 
Thanks for the fast answer @benorama !
