### ISSUE TITLE
Is this broken

### ISSUE THREAD

**Issue by hugosoli** [agorapulse/grails-aws-sdk#50]
Hi,
I have follow all the installation process.
It seems well installed since I can instantiate AmazonS3Service objects
howerver inside a service I have

CODECODE
import grails.plugin.awssdk.s3.*
......
       def runaws(){ //a function I know is working
                 AmazonS3Service amazonS3Service = new AmazonS3Service()
                amazonS3Service.listBucketNames()
      }
END OF CODE

and it fails.

2017-03-06 22:15:13.336 ERROR --- [nio-8080-exec-1] o.g.web.errors.GrailsExceptionResolver   : NullPointerException occurred when processing request: [GET] /api/composition
Cannot invoke method listBuckets() on null object. Stacktrace follows:

Am I doing something wrong? (I can´t find examples on the web)

**Comment by benorama** [comment]
Have you followed those instruction?
https://github.com/agorapulse/grails-aws-sdk/tree/master/grails-aws-sdk-s3

You should not create your own instance (`new AmazonS3Service`), Grails will do that for you.
You can then inject directly the service in your controller or service class:
```
class FooControllerOrService {
   AmazonS3Service amazonS3Service

  def someActionOrMethod() {
    amazonS3Service.listBucketNames()
  }
} 
```

**Comment by hugosoli** [comment]
Hi,
yes that is what I tried first and doing it again now.

I have in my file 
import grails.plugin.awssdk.s3.* //otherwhise it does not find tAmazons3Service

class ApiController {
     AmazonS3Service amazonS3Service

       def composition() {
            amazonS3Service.listBucketNames()
      }
}

When the controller is called I get 
I get this
onResolver   : NullPointerException occurred when processing request: [GET] /api/composition
Cannot invoke method listBuckets() on null object. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null

Still not working....

**Comment by hugosoli** [comment]
I have to say,
| Grails Version: 3.2.6
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_101
I have been working hours trying this pluging.... something is happening...

**Comment by benorama** [comment]
It looks like the `AmazonS3Client client` property is not initialized in your case.
This `client` property is initialized in `afterPropertiesSet()`
See in source code L.38:
https://github.com/agorapulse/grails-aws-sdk/blob/master/grails-aws-sdk-s3/grails-app/services/grails/plugin/awssdk/s3/AmazonS3Service.groovy

You might try to run your in debug mode and put a break point in this `afterPropertiesSet()` method to see if it is going through it.

**Comment by hugosoli** [comment]
Hi, thanks for your repply. I have never debug a grails app so (while I learn how to do it). I wonder if my application.yum could be wrong? It seems there is a typo in the installation example. Should it be
grails:
    pluging

or

grails:
    plugings
---
grails:
    profile: rest-api
    codegen:
        defaultPackage: sonodeaudioprocessing
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    plugin:
        awssdk:
            accessKey: bkbkbkb
            secretKey: blblblblblb
            s3:
                bucket: bkakashdjkhf
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

**Comment by hugosoli** [comment]
The parser of github adds wired fonts... Better attach file
[application.yml.zip](https://github.com/agorapulse/grails-aws-sdk/files/824857/application.yml.zip)

**Comment by hugosoli** [comment]
Hi, thanks for your repply. I have never debug a grails app so (while I learn how to do it). I wonder if my application.yum could be wrong? It seems there is a typo in the installation example. Should it be
grails:
pluging
or
grails:
plugings

[application.yml.zip](https://github.com/agorapulse/grails-aws-sdk/files/824867/application.yml.zip)

**Comment by hugosoli** [comment]
Hi!
I changed the key and secret key because I send it accidentally on the previous message and it is working. I guess my pairs where wrong... :(
Thank you very much for your kind help.
