### ISSUE TITLE
No such property: CannedAccessControlList

### ISSUE THREAD

**Issue by hugosoli** [agorapulse/grails-aws-sdk#51]
HI,
When I call 
amazonS3Service.storeFile('/composicion/sifunciona.wav', new File('composition3.wav'), CannedAccessControlList.PublicRead)

No such property: CannedAccessControlList for class: org.sonode.sap.ApiController.

It seems CannedAccessControlList belongs to aws-sdk
is grails-aws-sdk dependent of other pluging?

**Comment by benorama** [comment]
Have you imported the class?
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/CannedAccessControlList.html

I strongly recommend to use IntelliJ IDEA to develop Grails / Groovy app.

**Comment by benorama** [comment]
I'm closing the issue since no more feedback.
