### ISSUE TITLE
Socket not created by this factory

### ISSUE THREAD

**Issue by jjchiw** [agorapulse/grails-aws-sdk#52]
Hi, 

I'm using `grails` `3.2.8` with this version of the plugin `'org.grails.plugins:aws-sdk:1.10.74'` and "suddenly" it started to fail with "Socket not created by this factory", so doing a search I found this issue https://github.com/aws/aws-sdk-java/issues/1032....

So I added added `compile 'com.amazonaws:aws-java-sdk:1.11.115'` to my `build gradle` and it's working again

In our project we are only using `s3` so I'm not really sure what are the implications to the other services....

**Comment by benorama** [comment]
I guess  that you're using the legacy global AWS SDK plugin.
You might try to use the latest ones for Grails3, for example the one for S3:
https://github.com/agorapulse/grails-aws-sdk/tree/master/grails-aws-sdk-s3

**Comment by jjchiw** [comment]
Ah I see.....

Since we did a migration from `grails` `2.5.0` to `3.2x`  we just updated the plugins without noticing that you separated the plugin in multiple ones...

http://plugins.grails.org/plugin/agorapulse/aws-sdk-s3

Thanks, I'll update my dependencies :)
