### ISSUE TITLE
Setting awsJavaSdkVersion in my projects gradle.properties does not override default sdk

### ISSUE THREAD

**Issue by dda-mario-papi** [agorapulse/grails-aws-sdk#54]
I am attempting to set the aws sdk version to the most recent version of the sdk, 1.11.155.
Setting awsJavaSdkVersion in my projects gradle.properties does not seem to override default aws sdk version of 1.11.69 set by plugin.

**Comment by musketyr** [comment]
`awsJavaSdkVersion` is only internal property evaluated when the plugin is build on our side. have you tried to add the AWS dependency into your project. for example:

```
dependencies {
    // Latest AWS SDK
    compile "com.amazonaws:aws-java-sdk:1.11.160"
}
```

I'm closing this issue as this isn't anything we can do on our side but we can follow the conversation here.

**Comment by musketyr** [comment]
@dda-mario-papi you may also take a look here how to fine tune the dependency:

https://docs.gradle.org/3.5/userguide/dependency_management.html#sec:finetuning_the_dependency_resolution_process
