### ISSUE TITLE
grails-aws-sdk-ses returns 0 - any way to get more information?

### ISSUE THREAD

**Issue by mnellemann** [agorapulse/grails-aws-sdk#58]
Hi,

I'm trying to send mails with the grails-aws-sdk-ses plugin in my Grails 3.3.x app. I am able to send emails by using SMTP and my AWS credentials are allowed everything on ses. When I try to send  mail with any of the different send methods they all return 0  (not sent). Is there anyway to get more information about what's going on ?

Many thanks,
Mark

**Comment by mnellemann** [comment]
Hi,

I managed to get some more output by adding the following to my logback.groovy file;

```
logger('com.amazonaws', DEBUG, ['STDOUT'], false)
logger('org.apache.http.wire', DEBUG, ['STDOUT'], false)
```

Sorry about the noise :)

**Comment by musketyr** [comment]
Cool. So is there anything we can help you with?

pá 6. 10. 2017 13:19 odesílatel Mark Nellemann <notifications@github.com>
napsal:

**Comment by mnellemann** [comment]
No, it's all fine, i found my problem with the extra logging enabled. It might be useful in the docs though.
Thank you for quick response and awesome plugins.

**Comment by musketyr** [comment]
You're welcome!
