### ISSUE TITLE
Default bucket configuration

### ISSUE THREAD

**Issue by JeanAvila** [agorapulse/grails-aws-sdk#59]
I'm facing a problem with default bucket configuration. I did set the bucket name on "application.yml", but still don't work. 
I think the issue is around the 49th line of AmazonS3Service's, where 'defaultBucketName' is filled with '' when the ternary check fails.

Thanks everyone. 
Cheers.

**Comment by musketyr** [comment]
Can you attach the part of your configuration holding the value?

**Comment by JeanAvila** [comment]
Hi, musketyr, sure...

This is my config in "application.yml"
![config](https://user-images.githubusercontent.com/14995251/31336113-cf148d00-accb-11e7-9a19-ee6b2fb06aa0.png)

Those are the lines on AmazonS3Service.groovy that I think is where the problem is:

![pre_set](https://user-images.githubusercontent.com/14995251/31336160-098df476-accc-11e7-92ad-f2e158d25640.png)

and 
![get_service_config](https://user-images.githubusercontent.com/14995251/31336170-12752e42-accc-11e7-928b-268b8e4c6556.png)

Hi, musketyr, sure...

This is my config in "application.yml"
![config](https://user-images.githubusercontent.com/14995251/31336113-cf148d00-accb-11e7-9a19-ee6b2fb06aa0.png)

Those are the lines on AmazonS3Service.groovy that I think is where the problem is:

![pre_set](https://user-images.githubusercontent.com/14995251/31336160-098df476-accc-11e7-92ad-f2e158d25640.png)

and 
![get_service_config](https://user-images.githubusercontent.com/14995251/31336170-12752e42-accc-11e7-928b-268b8e4c6556.png)

When getServiceConfig method is called, it return only the value "S3" instead of the full set of configurations.
This makes fail the check "defaultBucketName = serviceConfig?.bucket ?: '' " on line 49.

I hope I have helped in some way

Thank you very much for your atention.

**Comment by musketyr** [comment]
thanks for the details. 

I believe you're missing `s3` configuration property. it should be:

```yaml
grails:
    plugin:
        awssdk:
            s3:
                bucket: myDefaultBucket
```

**Comment by JeanAvila** [comment]
Oh, you're right...

Now it's working properly.

Thank you very much for your help and your patience.
