### ISSUE TITLE
Allow Exceptions to propagate to implementing applications

### ISSUE THREAD

**Issue by emmanuj** [agorapulse/grails-aws-sdk#61]
I had some trouble figuring out why  `amazonS3Service.storeMultipartFile` was not working for me.
The logged exception in `amazonS3Service.storeInputStream` was not printing to STDOUT for me even after configuring logback to do so.
Would be nice if we can just wrap the calls in a try and catch and handle the response ourselves.

**Comment by musketyr** [comment]
how exactly have you configured `logback.groovy`? there is a special naming convention for grails services. I believe the name of the logger should be  `grails.app.services.grails.plugin.awssdk.s3.AmazonS3Service`. This request seems a bit problematic to me as starting to throw an exception may harm other users who already rely on the exception being caught.
