### ISSUE TITLE
SQS - How to work with multiple queues in same project

### ISSUE THREAD

**Issue by brunchey** [agorapulse/grails-aws-sdk#66]
Hello,  the documentation talks about being able to work with multiple queues.  How can I go about doing this?  Do I list them out comma seperated, do I add another sqs definition under awssdk in my application.yml? 

Thanks,
Ben

**Comment by benorama** [comment]
You can work with multiple queues with 2 options:
- use the default `amazonSQSQservice` and pass `queueName` as first parameter of each method,
e.g.: `amazonSQSService.sendMessage(queueName, messageBody)`
- or create an new service extending `amazonSQSService` and define the default queue in `@PostConstruct` (see README)
e.g.: `myFirstSQSService.sendMessage(messageBody)`

Does it answer your issue? Or do you want to be able to send a message to multiple queues in single call: `amazonSQSService.sendMessage(queueNames, messageBody)`

**Comment by brunchey** [comment]
thanks, this answers my question!
