### ISSUE TITLE
Sending to multiple recipients fails due to older jar dependency

### ISSUE THREAD

**Issue by romanye** [agorapulse/grails-aws-sdk#73]
Version 2.2.3 of the plugin throws this exception:
_**No signature of method: com.agorapulse.awssdk.ses.AwsSesMailer.send() is applicable for argument types: (java.util.ArrayList, java.lang.String, java.lang.String, java.lang.String, java.lang.String)**_

This exception stems from the fact that the jar file groovy-aws-sdk-ses-1.0.jar (located in the maven repository http://dl.bintray.com/agorapulse/libs/agorapulse/libs/groovy-aws-sdk-ses/1.0) is older and does not support the send() method in AwsSesMailer for multiple recipients.  

Can the jar files in http://dl.bintray.com/agorapulse/libs be updated?
Or, is there another a newer dependency repository for this plugin?

**Comment by musketyr** [comment]
Thank you for letting us know. I'll check what's the status of our libraries and let you know

**Comment by romanye** [comment]
Any ETA on when this will be done? The new version of our web app depends on these libraries and we have a planned release in a couple of weeks.

**Comment by musketyr** [comment]
fixed in 2.2.4
