### ISSUE TITLE
dynamodb data types

### ISSUE THREAD

**Issue by t2developer** [agorapulse/grails-aws-sdk#76]
for data modeling, how do I use a map or jsonobject like:

`@DynamoDBAttribute
Map complexObject
`
or

`@DynamoDBAttribute
JSONObject complexObject
`
Seems I have to define the schema and types clearly to get it to work correctly like nested class as in the dynamodb java docs are showing?

**Comment by musketyr** [comment]
I believe you are looking for this:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.ArbitraryDataMapping.html

**Comment by t2developer** [comment]
This seems like it basically splits up the fields and turns it into a string and vice versa, the converter would still have to know the data and types, I was hoping it can just take a json object and read it/split up the fields all dynamically. So I'm guessing I'll just have to store as a string and then read it back and do what I want with it.

**Comment by musketyr** [comment]
I believe that the field can be `Map` and that case it would work as you expect
