### ISSUE TITLE
AWS SQS FIFO queue not working

### ISSUE THREAD

**Issue by ChiranjibKarn** [agorapulse/grails-aws-sdk#82]
While trying to use FIFO queue in eu-west-1 region it throws following error 

> com.amazonaws.services.sqs.model.AmazonSQSException: Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 77f545fa-b011-5a89-ad39-115d161d5bc6)

Following is the configuration in application.yml

> accessKey: <my_access_key>
        secretKey: <my_secret_key>
        region: eu-west-1
        FifoQueue: true
        ContentBasedDeduplication: true

Any plan to support FIFO queue?

**Comment by musketyr** [comment]
since `2.2.6` you should be able to set `fifo: true` in the configuration to make the queue FIFO

**Comment by ChiranjibKarn** [comment]
When are you planning to release 2.2.6 version in Grails plugins repo? And, do I need to explicitly prefix ".fifo" in queue name (since as per AWS doc it is mandatory) ? Also, what would be deduplication setting? Hope, you will update the plugins doc as well?

**Comment by musketyr** [comment]
It should be already released.

I don't know really. I'm don't have any deeper knowledge about the FIFO queues now. You can always grab the `AmazonSQS` from the service and create the queue using the native client.

The afford is currently focused on porting this plugin for micronaut where the configuration will be more versatile and the documentation more detailed. So eventually I will update the docs here but this is currently low priority task.

**Comment by musketyr** [comment]
@ChiranjibKarn please try latest `2.2.10` release. now you should be able to add additionals attributes when the queue is created.

**Comment by ChiranjibKarn** [comment]
I did not see any changes in documentation. What would be the key/attribute name for setting "ContentBasedDeduplication" field? Also, in "AmazonSQSService.sendMessage" I do not see any changes, ho do I supposed to set "MessageGroupId" ?
It would be more helpful if you update the plugin's read me document according to the new change (support of FIFO). Thanks.

**Comment by ChiranjibKarn** [comment]
Are you planning to have these changes?

**Comment by musketyr** [comment]
please, see https://github.com/agorapulse/grails-aws-sdk/commit/c2e896f3f5d2f7ddf3863b1c8699311fef6a4ac5#diff-3d45ea4531e30642cb801031146a5febR142
