### ISSUE TITLE
creating extend service from AmazonSQSService throwing error "Can't have an abstract method in a non-abstract class"

### ISSUE THREAD

**Issue by venkymadala** [agorapulse/grails-aws-sdk#87]
**code :** 
```package sqssample

import grails.plugin.awssdk.sqs.AmazonSQSService
import org.springframework.beans.factory.annotation.Value

import javax.annotation.PostConstruct

class EmailQueueService extends AmazonSQSService {

    @Value('${grails.plugin.awssdk.sqs.queue}')
    private String QUEUE_NAME

    @PostConstruct
    def init() {
        init(QUEUE_NAME)
    }
}
```

**throwing error :**
```Can't have an abstract method in a non-abstract class. The class 'sqssample.EmailQueueService' must be declared abstract or the method 'reactor.bus.Bus sendAndReceive(java.lang.Object, groovy.lang.Closure)' must be implemented.```

**Comment by musketyr** [comment]
this looks like a mismatch of the Grails/Groovy versions. Which Grails and Groovy version are you using?

**Comment by musketyr** [comment]
closing for lack of response. feel free to reopen if required.
