### ISSUE TITLE
Could you public groovy-aws-sdk-util to Jcenter... please...

### ISSUE THREAD

**Issue by virtualdogbert** [agorapulse/grails-aws-sdk#92]
Could you please publish groovy-aws-sdk-util to jcenter, so that I wouldn't have to use your specific repository to use the Grails aws sdk plugins? It's pretty easy to setup through bintray:
https://bintray.com/agorapulse/libs/groovy-aws-sdk-util/1.1

Thanks

**Comment by musketyr** [comment]
I've opened a request, it should be approved and linked soon

**Comment by musketyr** [comment]
should be synced
